### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nhejazi** [PhilBoileau/cvCovEst#4]
+ [X] Setup repository `README.Rmd` file
  - [X] Draft description (for `DESCRIPTION` file also) 
  - [X] Installation instructions
  - [X] Toy example
  - [X] Issues sections
  - [X] Contributions
  - [X] License
+ [x] Identify classes of matrix objects we want to work with
+ [x] Create loss functions
+ [x] Identify estimators we want to consider. Determine if they are already implemented
